# --- L-System Parser/Mutator --- Lj Lapre ----------------------------------
18			
10				
200		
C	
C=LBW
B=[[''aH]|[g]]
a=Fs+;'a 			
g=Ft+;'g			
s=[::cc!!!!&&[FFcccZ]^^^^FFcccZ]
t=[c!!!!&[FF]^^FF]	
L=O			
O=P
P=Q
Q=R
R=U
U=X
X=Y
Y=V
V=[cc!!!&&&&&&&&&[Zp]|[Zp]]
p=h>>>>>>>>>>>>h>>>>>>>>>>>>h
h=[++++!F'''p]
H=[cccci[>>>>>dcFFF][<<<<<ecFFF]]
d=Z!&Z!&:'d		
e=Z!^Z!^:'e			
i=-:"i
W=[%[!!cb][<<<!!cb][>>>!!cb]]
b=Fl!+Fl+;'b			
l=[-cc{--z++z++z--|--z++z++z}]
@
