/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-05-13 19:57:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head lang=\"en\">\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Moodle</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"bootstrap-3.3.2-dist/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/jquery.js\"></script>\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/jquery.validate.min.js\"></script>\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/validatefacresitration.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/validateAssign.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/validatecourse.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/validateList.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/facultyRegis.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/AssignSubject.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/Addcourse.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/Search.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/searchfaculty.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/findstudent.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/searchAssignSubject.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/update.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"img/picto_navigation.png\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

if(null==session.getAttribute("name"))
{
	response.sendRedirect("login.jsp");
	return;
}
else
{
String  username=null;
username=(String)session.getAttribute("name");

      out.write("\r\n");
      out.write("<nav class=\"navbar  navbar-inverse navbar-fixed-top no-margin navbar-inner \" style=\"height: 30px\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("        <button type=\"button\" class=\"navbar-toggle collapsed \" data-toggle=\"collapse\" data-target=\"#bs-itm-navbar-collapse-1\">\r\n");
      out.write("            <span class=\"sr-only \">Toggle navigation</span>\r\n");
      out.write("            <span class=\"glyphicon glyphicon-play\" style=\"color: #ffffff\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <a class=\"navbar-brand w pull-left\" href=\"#\" style=\"top:2px\"><h4><b>ITMU Moodle</b></h4></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"collapse navbar-collapse navbar-right\" id=\"bs-itm-navbar-collapse-1\">\r\n");
      out.write("        <ul class=\"nav navbar-nav\">\r\n");
      out.write("           <li rol=\"presentation\" class=\"active\"><p><span class=\"glyphicon glyphicon-user\"></span>");
      out.print(username.toUpperCase() );
      out.write("&nbsp;&nbsp;&nbsp;<a href=\"/newmoodle/logout\" class=\"btn-sm btn-default\">Logout</a></p></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<br/><br/><br/>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("    <div class=\"col-md-3\">\r\n");
      out.write("        <div class=\"btn-group-vertical \" role=\"group\" aria-label=\"...\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-default disabled\"><b>ADD</b></button>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-lg btn-success\" data-toggle=\"modal\" data-target=\".addfaculty\">Register Faculty</button>\r\n");
      out.write("       <button type=\"button\" class=\"btn btn-lg btn-success\" data-toggle=\"modal\" data-target=\".assignsubject\">Assign Subject</button>\r\n");
      out.write("       <button type=\"button\" class=\"btn btn-lg btn-success\" data-toggle=\"modal\" data-target=\".addCourse\">Add Course & Subject Name</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-3 \">\r\n");
      out.write("        <div class=\"btn-group-vertical \" role=\"group\" aria-label=\"...\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-default disabled\"><b>SEARCH</b></button>\r\n");
      out.write("       <button type=\"button\" class=\"btn btn-lg btn-success\" data-toggle=\"modal\" data-target=\".listStudent\">List Student</button>\r\n");
      out.write("       <button type=\"button\" class=\"btn btn-lg btn-success\" data-toggle=\"modal\" data-target=\".listfaculty\">List Faculty</button>\r\n");
      out.write("       <button type=\"button\" class=\"btn btn-lg btn-success\" data-toggle=\"modal\" data-target=\".searchstudent\">Search Student</button>\r\n");
      out.write("       <button type=\"button\" class=\"btn btn-lg btn-success\" data-toggle=\"modal\" data-target=\".searchAssign\">Search Subject Assign</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-3\">\r\n");
      out.write("        <div class=\"btn-group-vertical \" role=\"group\" aria-label=\"...\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-default disabled\"><b>UPDATE</b></button>\r\n");
      out.write("           <button type=\"button\" class=\"btn btn-lg btn-success\" data-toggle=\"modal\" data-target=\".update\"><span class=\"glyphicon glyphicon-plus-sign\"></span>&nbsp;&nbsp;Update Student</button>\r\n");
      out.write("           <button type=\"button\" class=\"btn btn-lg btn-success\" data-toggle=\"modal\" data-target=\".question\"><span class=\"glyphicon glyphicon-plus-sign\"></span>&nbsp;&nbsp;Update Faculty</button>\r\n");
      out.write("           <button type=\"button\" class=\"btn btn-lg btn-success\" data-toggle=\"modal\" data-target=\".question\"><span class=\"glyphicon glyphicon-plus-sign\"></span>&nbsp;&nbsp;Update Assign Subject</button>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-3\">\r\n");
      out.write("        <div class=\"btn-group-vertical \" role=\"group\" aria-label=\"...\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-default disabled\"><b>DELETE</b></button>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-lg btn-success\" data-toggle=\"modal\" data-target=\".question\"><span class=\"glyphicon glyphicon-plus-sign\"></span>&nbsp;&nbsp;Delete Student</button>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-lg btn-success\" data-toggle=\"modal\" data-target=\".question\"><span class=\"glyphicon glyphicon-plus-sign\"></span>&nbsp;&nbsp;Delete Faculty</button>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-lg btn-success\" data-toggle=\"modal\" data-target=\".question\"><span class=\"glyphicon glyphicon-plus-sign\"></span>&nbsp;&nbsp;Delete Assign Subject</button>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade addfaculty\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLargeModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <h4 style=\"color: #2ec866\"><b> Faculty Registration</b></h4>\r\n");
      out.write("            <div class=\"login-form\">\r\n");
      out.write("                <form class=\"form-group\" method=\"post\" action=\"/newmoodle/factlyRegis\" id=\"facultyregis\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"input-group input-group-sm\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" name=\"username\" placeholder=\"Username /Factid\" id=\"username\">\r\n");
      out.write("                        <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-user\"></span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"text-error\" class=\"error\" for=\"username\"></label>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"input-group input-group-sm\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" placeholder=\"Name\" id=\"name\" name=\"name\">\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-user\"></span></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"name-error\" class=\"error\" for=\"name\"></label>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"input-group input-group-sm\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" placeholder=\"DepartMent\" id=\"dept\" name=\"dept\">\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-user\"></span></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"dept-error\" class=\"error\" for=\"dept\"></label>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"input-group input-group-sm\">\r\n");
      out.write("                            <input type=\"password\" class=\"form-control\" placeholder=\"Password\" id=\"fpassword\" name=\"fpassword\">\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-lock\"></span></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"fpassword-error\" class=\"error\" for=\"fpassword\"></label>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"input-group input-group-sm\">\r\n");
      out.write("                            <input type=\"password\" class=\"form-control\" placeholder=\" Confirm Password\" id=\"fcpassword\" name=\"fcpassword\">\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-lock\"></span></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"fcpassword-error\" class=\"error\" for=\"fcpassword\"></label>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"input-group input-group-sm\">\r\n");
      out.write("                            <input type=\"email\" class=\"form-control\" placeholder=\"Email ID\" id=\"femail\" name=\"femail\">\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-envelope\"></span></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"email-error\" class=\"error\" for=\"femail\"></label>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"input-group input-group-sm\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" placeholder=\"Mobile No\" id=\"Fmobile\" name=\"Fmobile\">\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-phone\"></span></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"fmbile-error\" class=\"error\" for=\"Fmobile\"></label>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"input-group input-group-sm\">\r\n");
      out.write("                            <input type=\"date\" class=\"form-control dateclass placeholderclass\" placeholder=\"Date of Birth\" id=\"dob\" name=\"dob\" onclick=\"$(this).removeClass('placeholderclass')\">\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-calendar\"></span></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"date-error\" class=\"error\" for=\"dob\"></label>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-success  center-block\">Register</button>\r\n");
      out.write("\t\t\t\t\t<div id=\"mesg\" style=\"color:red\"></div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("<div class=\"modal fade assignsubject\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLargeModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <h4 style=\"color: #2ec866\"><b>Assign Subject & Faculty</b></h4>\r\n");
      out.write("            <div class=\"login-form\">\r\n");
      out.write("                <form class=\"form-group\" method=\"post\" action=\"/newmoodle/AssignSubject\" id=\"assign\" >\r\n");
      out.write("                    <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please Enter FacultyId\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" name=\"facid\" placeholder=\"facultyid\" id=\"facid\" >\r\n");
      out.write("                        <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-user\"></span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"facid-error\" class=\"error\" for=\"facid\"></label>\r\n");
      out.write("                        <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please Enter Subject Name\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" placeholder=\"SubjectName\" id=\"subname\" name=\"subname\">\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-flash\"></span></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    <label id=\"subname-error\" class=\"error\" for=\"subname\"></label>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please Enter SubjectId\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" placeholder=\"Subject Id\" id=\"subid\" name=\"subid\">\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-asterisk\"></span></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    <label id=\"subid-error\" class=\"error\" for=\"subid\"></label>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please Enter Branch\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" placeholder=\"Branch\" id=\"branch\" name=\"branch\">\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-pencil\"></span></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    <label id=\"branch-error\" class=\"error\" for=\"branch\"></label>\r\n");
      out.write("                        <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please Select Semester\">\r\n");
      out.write("                            <select class=\"form-control\" id=\"semester\" name=\"semester\">\r\n");
      out.write("                                <option selected value=\"\">Select Semester</option>\r\n");
      out.write("                                <option value=\"1\">1</option>\r\n");
      out.write("                                <option value=\"2\">2</option>\r\n");
      out.write("                                <option value=\"3\">3</option>\r\n");
      out.write("                                <option value=\"4\">4</option>\r\n");
      out.write("                                <option value=\"5\">5</option>\r\n");
      out.write("                                <option value=\"6\">6</option>\r\n");
      out.write("                                <option value=\"7\">7</option>\r\n");
      out.write("                                <option value=\"8\">8</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-triangle-left\"></span></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    <label id=\"sem-error\" class=\"error\" for=\"semester\"></label><br/>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-success  center-block\">Assign</button>\r\n");
      out.write("\t\t\t\t\t<div id=\"resmesg\" style=\"color:red\"></div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"modal fade addCourse\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLargeModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <h4 style=\"color: #2ec866\"><b>Add Course and subject Info</b></h4>\r\n");
      out.write("            <div class=\"login-form\">\r\n");
      out.write("                <form class=\"form-group\" method=\"post\" action=\"/newmoodle/AddSubject\" id=\"course\" >\r\n");
      out.write("                    <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please Enter SubjectId\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" name=\"subjectid\" placeholder=\"Enter Subject ID\" id=\"subjectid\" >\r\n");
      out.write("                        <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-user\"></span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"subjectid-error\" class=\"error\" for=\"subjectid\"></label>\r\n");
      out.write("                    <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please Enter Subject Name\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"Enter SubjectName\" id=\"subjectname\" name=\"subjectname\">\r\n");
      out.write("                        <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-flash\"></span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"subjectname-error\" class=\"error\" for=\"subjectname\"></label>\r\n");
      out.write("                    <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please Enter Course\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"Enter Branch\" id=\"branchid\" name=\"branchid\">\r\n");
      out.write("                        <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-pencil\"></span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <label id=\"course-error\" class=\"error\" for=\"branchid\"></label>\r\n");
      out.write("                    <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please Select Semester\">\r\n");
      out.write("                        <select class=\"form-control\" id=\"sem\" name=\"sem\">\r\n");
      out.write("                            <option selected value=\"\">Select Semester</option>\r\n");
      out.write("                            <option value=\"1\">1</option>\r\n");
      out.write("                            <option value=\"2\">2</option>\r\n");
      out.write("                            <option value=\"3\">3</option>\r\n");
      out.write("                            <option value=\"4\">4</option>\r\n");
      out.write("                            <option value=\"5\">5</option>\r\n");
      out.write("                            <option value=\"6\">6</option>\r\n");
      out.write("                            <option value=\"7\">7</option>\r\n");
      out.write("                            <option value=\"8\">8</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-triangle-left\"></span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"semester-error\" class=\"error\" for=\"sem\"></label>\r\n");
      out.write("                    <br/>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-success  center-block\">ADD</button>\r\n");
      out.write("\t\t\t\t\t<div id=\"submesg\" style=\"color:red\"></div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"modal fade listStudent\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLargeModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <h4 style=\"color: #2ec866\"><b>Select Student List</b></h4>\r\n");
      out.write("            <div class=\"login-form\">\r\n");
      out.write("                <form class=\"form-group\" method=\"get\" action=\"/newmoodle/searchstudent\" id=\"list\" >\r\n");
      out.write("                    <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please Select Branch\">\r\n");
      out.write("                        <select class=\"form-control\" id=\"courseid\" name=\"courseid\">\r\n");
      out.write("                            <option selected value=\"\">Select Branch</option>\r\n");
      out.write("                            <option value=\"mca\">MCA</option>\r\n");
      out.write("                            <option value=\"bca\">BCA</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-triangle-left\"></span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"courseid-error\" class=\"error\" for=\"courseid\"></label>\r\n");
      out.write("                    <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please Select Semester\">\r\n");
      out.write("                        <select class=\"form-control\" id=\"semid\" name=\"semid\">\r\n");
      out.write("                            <option selected value=\"\">Select Semester</option>\r\n");
      out.write("                            <option value=\"1\">1</option>\r\n");
      out.write("                            <option value=\"2\">2</option>\r\n");
      out.write("                            <option value=\"3\">3</option>\r\n");
      out.write("                            <option value=\"4\">4</option>\r\n");
      out.write("                            <option value=\"5\">5</option>\r\n");
      out.write("                            <option value=\"6\">6</option>\r\n");
      out.write("                            <option value=\"7\">7</option>\r\n");
      out.write("                            <option value=\"8\">8</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-triangle-left\"></span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"semid-error\" class=\"error\" for=\"semid\"></label>\r\n");
      out.write("                    <br/>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-success  pull-right\">Search</button>\r\n");
      out.write(" <div id=\"ss\" style=\"color:red\"></div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"modal fade searchstudent\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLargeModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <h4 style=\"color: #2ec866\"><b>Search Student </b></h4>\r\n");
      out.write("            <div class=\"login-form\">\r\n");
      out.write("                <form class=\"form-group\" method=\"get\" action=\"/newmoodle/findstudent\" id=\"searchstudent\" >\r\n");
      out.write("                    <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please Select Branch\">\r\n");
      out.write("                        <select class=\"form-control\" id=\"scourse\" name=\"scourse\" required>\r\n");
      out.write("                            <option selected value=\"\">Select Branch</option>\r\n");
      out.write("                            <option value=\"mca\">MCA</option>\r\n");
      out.write("                            <option value=\"bca\">BCA</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-triangle-left\"></span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"scourse-error\" class=\"error\" for=\"scourse\"></label>\r\n");
      out.write("                    <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please Enter Student Name\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" name=\"sname\" placeholder=\"Enter Student Name\" id=\"sname\" required>\r\n");
      out.write("                        <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-user\"></span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"sname-error\" class=\"error\" for=\"sname\"></label>\r\n");
      out.write("                    <br/>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-success  pull-right\">Search</button>\r\n");
      out.write("                   \r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"modal fade listfaculty\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLargeModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <h4 style=\"color: #2ec866\"><b>Select Faculty List</b></h4>\r\n");
      out.write("            <div class=\"login-form\">\r\n");
      out.write("                <form class=\"form-group\" method=\"get\" action=\"/newmoodle/searchfaculty\" id=\"listfac\" >\r\n");
      out.write("                    <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please Select Branch\">\r\n");
      out.write("                        <select class=\"form-control\" id=\"department\" name=\"department\" required>\r\n");
      out.write("                            <option selected value=\"\">Select Deaprtament</option>\r\n");
      out.write("                            <option value=\"soca\">SOCA</option>\r\n");
      out.write("                            <option value=\"soet\">SOET</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-triangle-left\"></span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <br/>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-success  pull-right\">Search</button>\r\n");
      out.write("                    <div id=\"fac\" style=\"color:red\"></div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"modal fade searchAssign\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLargeModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <h4 style=\"color: #2ec866\"><b>Search Assign Subject </b></h4>\r\n");
      out.write("            <div class=\"login-form\">\r\n");
      out.write("                <form class=\"form-group\" method=\"get\" action=\"/newmoodle/searchAssignSubject\" id=\"searchassign\">\r\n");
      out.write("                    <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please Select Branch\">\r\n");
      out.write("                        <select class=\"form-control\" id=\"sfcourse\" name=\"sfcourse\" required>\r\n");
      out.write("                            <option selected value=\"\">Select Branch</option>\r\n");
      out.write("                            <option value=\"mca\">MCA</option>\r\n");
      out.write("                            <option value=\"bca\">BCA</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-triangle-left\"></span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"scourses-error\" class=\"error\" for=\"sfcourse\"></label>\r\n");
      out.write("                    <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please Enter Subject Code\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" name=\"scode\" placeholder=\"Enter Subject Code(E.g MCA-405)\" id=\"scode\" required>\r\n");
      out.write("                        <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-user\"></span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"scode-error\" class=\"error\" for=\"scode\"></label>\r\n");
      out.write("                    <br/>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-success  pull-right\">Search</button>\r\n");
      out.write("                    <div id=\"ssubject\" style=\"color:red\"></div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"modal fade update\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLargeModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <h4 style=\"color: #2ec866\"><b>Update Student </b></h4>\r\n");
      out.write("            <div class=\"login-form\">\r\n");
      out.write("                <form class=\"form-group\" method=\"get\" action=\"/newmoodle/findstudentforupdate\" id=\"updatestudent\" >\r\n");
      out.write("                    <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please Select Branch\">\r\n");
      out.write("                        <select class=\"form-control\" id=\"ucourse\" name=\"ucourse\" required>\r\n");
      out.write("                            <option selected value=\"\">Select Branch</option>\r\n");
      out.write("                            <option value=\"mca\">MCA</option>\r\n");
      out.write("                            <option value=\"bca\">BCA</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-triangle-left\"></span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"scourse-error\" class=\"error\" for=\"scourse\"></label>\r\n");
      out.write("                    <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please Enter Student id\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" name=\"uname\" placeholder=\"Enter Student id\" id=\"uname\" required>\r\n");
      out.write("                        <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-user\"></span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"sname-error\" class=\"error\" for=\"uname\"></label>\r\n");
      out.write("                    <br/>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-success  pull-right\">Update</button>\r\n");
      out.write("                    <div id=\"up\" style=\"color:red\"></div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<hr/>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<table class=\"table table-bordered hide table-hover table-condensed table-reponsive\" id=\"td\" style=\"background-color:white\">\r\n");
      out.write("<tr>\r\n");
      out.write("<th class=\"success\">NAME</th>\r\n");
      out.write("<th class=\"success\">ROLL NO.</th>\r\n");
      out.write("<th class=\"success\">EMAIL</th>\r\n");
      out.write("<th class=\"success\">DOB</th>\r\n");
      out.write("<th class=\"success\">COURSE</th>\r\n");
      out.write("<th class=\"success\">SEMESTER</th>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table class=\"table table-bordered hide table-hover table-condensed table-reponsive\" id=\"tds\" style=\"background-color:white\">\r\n");
      out.write("<tr>\r\n");
      out.write("<th class=\"success\">NAME</th>\r\n");
      out.write("<th class=\"success\">ROLL NO.</th>\r\n");
      out.write("<th class=\"success\">EMAIL</th>\r\n");
      out.write("<th class=\"success\">DOB</th>\r\n");
      out.write("<th class=\"success\">COURSE</th>\r\n");
      out.write("<th class=\"success\">SEMESTER</th>\r\n");
      out.write("<th class=\"success\">PASSWORD</th>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table class=\"table table-bordered hide table-hover table-condensed table-reponsive\" id=\"tdf\" style=\"background-color:white\">\r\n");
      out.write("<tr>\r\n");
      out.write("<th class=\"success\">NAME</th>\r\n");
      out.write("<th class=\"success\">ID.</th>\r\n");
      out.write("<th class=\"success\">EMAIL</th>\r\n");
      out.write("<th class=\"success\">DOB</th>\r\n");
      out.write("<th class=\"success\">MOBILE NO.</th>\r\n");
      out.write("<th class=\"success\">DEPARTMENT</th>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table class=\"table table-bordered hide table-hover table-condensed table-reponsive\" id=\"tdsub\" style=\"background-color:white\">\r\n");
      out.write("<tr>\r\n");
      out.write("<th class=\"success\">SUBJECT-NAME</th>\r\n");
      out.write("<th class=\"success\">SUBJECT-CODE</th>\r\n");
      out.write("<th class=\"success\">COURSE</th>\r\n");
      out.write("<th class=\"success\">FACULTYID</th>\r\n");
      out.write("<th class=\"success\">SEMESTER</th>\r\n");
      out.write("<th class=\"success\">FACULTYNAME</th>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<div class=\"container\" id=\"studentupdate\" style=\"width:500px\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $( document ).ready(function() {\r\n");
      out.write("        $(\"[data-toggle=tooltip]\").tooltip();\r\n");
      out.write("    });</script>\r\n");
 } 
      out.write("\r\n");
      out.write("<script src=\"bootstrap-3.3.2-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
