/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-05-14 14:38:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head lang=\"en\">\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Moodle</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"bootstrap-3.3.2-dist/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/jquery.js\"></script>\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/jquery.validate.min.js\"></script>\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/validate.js\" ></script>\r\n");
      out.write("        <script src=\"bootstrap-3.3.2-dist/js/login.js\" ></script>\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/insert.js\" ></script>\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/changePasssword.js\" ></script>\r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write(" <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"img/picto_navigation.png\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-fixed-top navbar-inverse  no-margin navbar-inner \" style=\"height: 30px\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle collapsed \" data-toggle=\"collapse\" data-target=\"#bs-itm-navbar-collapse-1\">\r\n");
      out.write("                <span class=\"sr-only \">Toggle navigation</span>\r\n");
      out.write("                <span class=\"glyphicon glyphicon-play\" style=\"color: #ffffff\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <a class=\"navbar-brand w pull-left\" href=\"#\" style=\"top:2px\"><h4><b>ITMU Moodle</b></h4></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"collapse navbar-collapse navbar-right\" id=\"bs-itm-navbar-collapse-1\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("                <li rol=\"presentation\"><a href=\"First.jsp\">Home</a> </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"col-lg-12\">\r\n");
      out.write("<div class=\"panel panel-default\" style=\"background-color: #dcdcdc;background-color: rgba(255,255,255,0.6);\">\r\n");
      out.write("    <div class=\"panel-heading\" style=\"background-color:#1abc9c;color:white!important;\"><p><strong>Login To Your Account/ Register New</strong></p></div>\r\n");
      out.write("    <div class=\"panel-body\">\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("            <h3 style=\"color: #000000\">Log In</h3>\r\n");
      out.write("            <div class=\"login-form\">\r\n");
      out.write("            \r\n");
      out.write("  \t\t\t\t <form class=\"form-group\" method=\"post\" action=\"/newmoodle/login\" id=\"login\">\r\n");
      out.write("  \t\t\t\t <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"input-group input-group-lg\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" name=\"username\" placeholder=\"Username\" id=\"username\">\r\n");
      out.write("                        <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-user\"></span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label id=\"usrname-error\" class=\"error\" for=\"username\"></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"input-group input-group-lg\">\r\n");
      out.write("                            <input type=\"password\" class=\"form-control\" placeholder=\"Password\" id=\"password\" name=\"password\">\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-lock\"></span></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label id=\"ppassword-error\" class=\"error\" for=\"password\"></label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"form-group  \">\r\n");
      out.write("                            <div class=\"input-group input-group-lg\">\r\n");
      out.write("                                <label for=\"student\" id=\"std\"><input type=\"radio\" id=\"user\" name=\"user\" value=\"student\" name=\"user\"/>Student</label>&nbsp;&nbsp;\r\n");
      out.write("                                <label for=\"admin\" id=\"ad\"><input type=\"radio\" id=\"user\" value=\"admin\"  name=\"user\"/>Admin</label>&nbsp;&nbsp;\r\n");
      out.write("                                <label for=\"faculty\" id=\"fac\"><input type=\"radio\" id=\"user\" value=\"faculty\" name=\"user\"/>Faculty</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button class=\"btn btn-primary btn-lg btn-block\" type=\"submit\" >Log in</button>\r\n");
      out.write("                        <div id=\"mesg\"> </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <a class=\"login-link\" data-toggle=\"modal\" data-target=\".changePassword\">Lost your password?</a>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"modal fade changePassword\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLargeModalLabel\" aria-hidden=\"true\" data-backdrop=\"static\" data-keyboard=\"false\">\r\n");
      out.write("                            <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("                                <div class=\"modal-content\">\r\n");
      out.write("                                <div class=\"modal-header\" style=\"background-color:#1abc9c;\">\r\n");
      out.write("        \t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("        \t\t<h4 class=\"modal-title\" style=\"text-align:center\" ><b>Change Your Password </b></h4>\r\n");
      out.write("     \t\t\t\t\t </div>\r\n");
      out.write("                                    <div class=\"login-form\">\r\n");
      out.write("                                    \r\n");
      out.write("                                        <form class=\"form-group\" method=\"post\" action=\"/newmoodle/changePassword\" id=\"change\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <div class=\"input-group input-group-sm\">\r\n");
      out.write("                                                <input type=\"text\" class=\"form-control\"  placeholder=\"Username\" id=\"fusername\" name=\"fusername\">\r\n");
      out.write("                                                <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-user\"></span></div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <label id=\"usrname-error\" class=\"error\" for=\"fusername\"></label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            \r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <div class=\"input-group input-group-sm\">\r\n");
      out.write("                                                    <input type=\"password\" class=\"form-control\" placeholder=\"Password\" id=\"fpassword\" name=\"fpassword\">\r\n");
      out.write("                                                    <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-lock\"></span></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                     <label id=\"ppassword-error\" class=\"error\" for=\"fpassword\"></label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            \r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <div class=\"input-group input-group-sm\">\r\n");
      out.write("                                                    <input type=\"password\" class=\"form-control\" placeholder=\"Confirm Password\" id=\"fcpassword\" name=\"fcpassword\">\r\n");
      out.write("                                                    <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-lock\"></span></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <label id=\"ppassword-error\" class=\"error\" for=\"fcpassword\"></label>\r\n");
      out.write("                                                \r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <div class=\"input-group input-group-sm\">\r\n");
      out.write("                                                    <input type=\"date\" class=\"form-control dateclass placeholderclass\" placeholder=\"Date of Birth\" id=\"dob\" name=\"dob\" onclick=\"$(this).removeClass('placeholderclass')\">\r\n");
      out.write("                                                    <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-lock\"></span></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <label id=\"DOB-error\" class=\"error\" for=\"dob\"></label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <label style=\"color:#16A085\">Please select</label>\r\n");
      out.write("                                            <div class=\"form-group  \">\r\n");
      out.write("                            <div class=\"input-group input-group-lg\">\r\n");
      out.write("                                <label for=\"student\" id=\"std\"><input type=\"radio\" id=\"cuser\" name=\"cuser\" value=\"student\" name=\"user\"/>Student</label>&nbsp;&nbsp;\r\n");
      out.write("                                <label for=\"admin\" id=\"ad\"><input type=\"radio\" id=\"cuser\" value=\"admin\"  name=\"cuser\"/>Admin</label>&nbsp;&nbsp;\r\n");
      out.write("                                <label for=\"faculty\" id=\"fac\"><input type=\"radio\" id=\"cuser\" value=\"faculty\" name=\"cuser\"/>Faculty</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                                            <button type=\"submit\" class=\"btn btn-primary\">Change</button>\r\n");
      out.write("                                            <div id=\"resp\" style=\"color:red\"></div>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("            <h3 style=\"color: #000000\">Sign up New Account</h3>\r\n");
      out.write("            <div class=\"login-form\">\r\n");
      out.write("                <form class=\"form-group\" action=\"/newmoodle/student_signup\" method=\"Post\" id=\"signup\">\r\n");
      out.write("                    <div class=\"form-group \">\r\n");
      out.write("                        <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"please enter your name\" >\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-user\"></span></div>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" placeholder=\"name\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label id=\"text-error\" class=\"error\" for=\"name\"></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group \">\r\n");
      out.write("                        <div class=\"input-group input-group-sm\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"please enter Roll no\" >\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-user\"></span></div>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"rollno\" name=\"rollno\" placeholder=\"Roll-No\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label id=\"rollno-error\" class=\"error\" for=\"rollno\"></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"input-group  input-group-sm\"  data-toggle=\"tooltip\" data-placement=\"left\" title=\"please enter at least 8 character long password\">\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-lock\"></span></div>\r\n");
      out.write("                            <input type=\"password\" class=\"form-control\" id=\"Password\" name=\"Password\" placeholder=\"password\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label id=\"password-error\" class=\"error\" for=\"Password\"></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"input-group  input-group-sm\"  data-toggle=\"tooltip\" data-placement=\"left\" title=\"Reapeat password\">\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-lock\"></span></div>\r\n");
      out.write("                            <input type=\"password\" class=\"form-control\" id=\"Rpassword\" name=\"Rpassword\" placeholder=\"Confirm-password\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label id=\"Rpassword-error\" class=\"error\" for=\"Rpassword\"></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"input-group  input-group-sm\"  data-toggle=\"tooltip\" data-placement=\"left\" title=\"please enter valid email id\">\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-envelope\" ></span> </div>\r\n");
      out.write("                            <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" placeholder=\"email\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label id=\"email-error\" class=\"error\" for=\"email\"></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"input-group  input-group-sm\"  data-toggle=\"tooltip\" data-placement=\"left\" title=\"please enter your course\">\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-book\"></span> </div>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"course\" name=\"course\" placeholder=\"Course\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label id=\"course-error\" class=\"error\" for=\"course\"></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"input-group  input-group-sm\"  data-toggle=\"tooltip\" data-placement=\"left\" title=\"please enter your semester\">\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-book\"></span> </div>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"sem\" placeholder=\"semester\" name=\"sem\" >\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label id=\"sem-error\" class=\"error\" for=\"sem\"></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"input-group  input-group-sm\"  data-toggle=\"tooltip\" data-placement=\"left\" title=\"please enter your Date of Bitrh\">\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-book\"></span> </div>\r\n");
      out.write("                            <input type=\"date\" class=\"form-control\" id=\"DOB\" placeholder=\"DOB\" name=\"DOB\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label id=\"DOB-error\" class=\"error\" for=\"DOB\"></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-success center-block\" value=\"login\" id=\"btn\">Sign Up</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div></div></div>\r\n");
      out.write("                    <script type=\"text/javascript\">\r\n");
      out.write("                        $( document ).ready(function() {\r\n");
      out.write("                            $(\"[data-toggle=tooltip]\").tooltip();\r\n");
      out.write("                        });</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"bootstrap-3.3.2-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
