/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-05-13 17:19:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head lang=\"en\">\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Moodle</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"bootstrap-3.3.2-dist/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/jquery.js\"></script>\r\n");
      out.write("    <script src=\"bootstrap-3.3.2-dist/js/login.js\" ></script>\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"img/picto_navigation.png\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"white\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"login\">\r\n");
      out.write("        <div id=\"flat\">\r\n");
      out.write("            <div class=\"login-icon\">\r\n");
      out.write("                <img src=\"img/picto_navigation.png\" alt=\"welcome\">\r\n");
      out.write("                <h4>Welcome to Moodle</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"login-form\">\r\n");
      out.write("            <div id=\"mesg\"></div>\r\n");
      out.write("                <form class=\"form-group\" method=\"post\" action=\"/newmoodle/login\" id=\"login\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"input-group input-group-lg\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" name=\"username\" placeholder=\"Username\" id=\"username\" required>\r\n");
      out.write("                        <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-user\"></span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <label for=\"username\"></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"input-group input-group-lg\">\r\n");
      out.write("                            <input type=\"password\" class=\"form-control\" placeholder=\"Password\" id=\"password\" required>\r\n");
      out.write("                            <div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-lock\"></span></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label for=\"password\"></label>\r\n");
      out.write("                     \r\n");
      out.write("                                <label for=\"student\" id=\"std\"><input type=\"radio\" id=\"user\" value=\"student\" name=\"user\"/>Student</label>&nbsp;&nbsp;\r\n");
      out.write("                                <label for=\"admin\" id=\"ad\"><input type=\"radio\" id=\"user\" value=\"admin\" name=\"user\"/>Admin</label>&nbsp;&nbsp;\r\n");
      out.write("                                <label for=\"faculty\" id=\"fac\"><input type=\"radio\" id=\"user\" value=\"faculty\" name=\"user\"/>Faculty</label>\r\n");
      out.write("                          \r\n");
      out.write("                        \r\n");
      out.write("             <button type=\"submit\" class=\"btn btn-primary btn-lg btn-block\" >Log in</button>\r\n");
      out.write("                       \r\n");
      out.write("            </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("<script src=\"bootstrap-3.3.2-dist/js/jquery.js\"></script>\r\n");
      out.write("<script src=\"bootstrap-3.3.2-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
